### ISSUE TITLE
And Here's The PP, ghost and lots of other things error.

### ISSUE THREAD

**Issue by Lykayos** [Lykayos/Clean-Bay-copy-No-Commit-History#70]
proc name: mergeAtoms (/proc/mergeAtoms)
  source file: lists.dm,234
  usr: Karen Lingard (/mob/dead/observer)
  src: null
  call stack:
mergeAtoms(/list (/list), /list (/list), 1)
sortAtom(/list (/list), 1)
sortAtom(/list (/list), 1)
sortAtom(/list (/list), 1)
sortAtom(/list (/list), 1)
sortAtom(/list (/list), 1)
sortmobs()

**Comment by Lykayos** [comment]
This may be caused by #68

**Comment by JakeDaBoss** [comment]
Fixed by Scopes.
