### ISSUE TITLE
Disposals has been laid incorrectly.

### ISSUE THREAD

**Issue by JakeDaBoss** [Lykayos/Clean-Bay-copy-No-Commit-History#81]
My fault. The disposal loop sometimes deposits garbage and in less frequent occasions - humans - into Misc. Science.

**Comment by Lykayos** [comment]
Going to check and pull #80 and fix this in a moment.

**Comment by JakeDaBoss** [comment]
Still not fixed.

**Comment by JakeDaBoss** [comment]
Fucking fixed. Nevermind.
