### ISSUE TITLE
Law book incorrect linking.

### ISSUE THREAD

**Issue by JakeDaBoss** [Lykayos/Clean-Bay-copy-No-Commit-History#82]

**Comment by Lykayos** [comment]
This happens every time bay changes their wiki set up.

**Comment by JakeDaBoss** [comment]
We have our own laws on our wiki...


Verzonden vanaf mijn Samsung-apparaat

-------- Oorspronkelijk bericht --------
Van: Lykayos <notifications@github.com>
Datum: 09-03-2016  02:50  (GMT+01:00)
Aan: Lykayos/Clean-Bay-copy-No-Commit-History <Clean-Bay-copy-No-Commit-History@noreply.github.com>
Cc: Jake Miles <visiongamingjake@hotmail.com>
Onderwerp: Re: [Clean-Bay-copy-No-Commit-History] Law book incorrect linking. (#82)

This happens every time bay changes their wiki set up.


---
