### ISSUE TITLE
Clear toxin/fire in zone does not display admin log.

### ISSUE THREAD

**Issue by JakeDaBoss** [Lykayos/Clean-Bay-copy-No-Commit-History#85]

**Comment by Mewchild** [comment]
I think it may actually be fore the best that this doesn't create a log, to be honest. This is one of those verbs that often requires multiple uses to get the job done (as canisters empty, air normalizes, etc etc), which can lead to flooding of logs in the event of grief.

**Comment by JakeDaBoss** [comment]
Closed. After reconsideration, I think Mew is right.
