### ISSUE TITLE
Station naming incorrect.

### ISSUE THREAD

**Issue by DJPantheris** [Lykayos/Clean-Bay-copy-No-Commit-History#87]
The ATMs text has an area where it reads "NSS Exodus" and I think that should be "NSS Prospector"

Edit by Jake;

This goes for the entire station.

**Comment by EmergencyTemporalShift** [comment]
I changed all the strings in the code to fix this only to find that I couldn't merge them. :|

**Comment by JakeDaBoss** [comment]
@EmergencyTemporalShift We allow users to create pull requests. We can't just allow any user to upload anything they want.

**Comment by EmergencyTemporalShift** [comment]
@JakeDaBoss Yes, I understand, but whats the worst that could possibly happen? :)

**Comment by JakeDaBoss** [comment]
@EmergencyTemporalShift Anyone with collaborator access can damage our existing github beyond repair. Lykayos would have to roll back any changes, and create an entire new Git repo. All of our history and collaborators would be gone.

**Comment by EmergencyTemporalShift** [comment]
@JakeDaBoss That's not that bad, pshaaaah.

**Comment by JakeDaBoss** [comment]
@EmergencyTemporalShift That's because you don't have to do what we have to do if that happens.

**Comment by Lykayos** [comment]
Fixed by e6b19436 .

**Comment by Lykayos** [comment]
@EmergencyTemporalShift If you can't merge something chances are you're fork went stale. Refork or reset it so it's synced with the origin, my branch, again.
